// components/svelte/Picture.svelte
<script lang="ts">

	import Img from './Img.svelte';
	import { PictireProps, mapSources, classToString, styleToString } from '../index';

	export let src: PictireProps['src'];
	export let alt: PictireProps['alt'];
	export let formats: PictireProps['formats'];
	export let adaptiveMode: PictireProps['adaptiveMode'];
	export let classList: PictireProps['class'];
	export let imgClass: PictireProps['imgClass'];
	export let style: PictireProps['style'];
	export let imgStyle: PictireProps['imgStyle'];
	export let lazy: PictireProps['lazy'];
	export let sizes: PictireProps['sizes'];
	export let draggable: PictireProps['draggable'];

	const sources = mapSources(src, formats, adaptiveMode);

</script>

<picture class={classToString(classList)} style={styleToString(style)} data-ssga-id="picture:svelte">
	
	{#each sources as item}
		<source srcset={item.source} type={item.type} media={item.media} />
	{/each}
	
	<Img src={src} alt={alt} draggable={draggable} lazy={lazy} sizes={sizes} classList={imgClass} style={imgStyle} />

</picture>

// components/react/Picture.tsx
import Img from "./Img.jsx";
import { PictireProps, mapSources, adaptBaseImageUrl, classToString, styleToString } from '../index';

/**
 * Advanced \<picture\> component
 */
export default (props: PictireProps) => {

	const sources = mapSources(props.src, props.formats, props.adaptiveModes);

	return (
		<picture className={classToString(props.class)} style={styleToString(props.style)} data-component-id="ssga:picture:react">
			{ sources.map(item => (
				<source srcset={item.source} type={item.type} media={item.media as string | undefined} />
			)) }
			<Img src={adaptBaseImageUrl(props.src, props.adaptiveModes)} alt={props.alt} draggable={props.draggable} lazy={props.lazy} sizes={props.sizes} class={props.imgClass} style={props.imgStyle} />
		</picture>
	);
};
