// components/vue/Picture.vue
<script setup lang="ts">

import Img from './Img.vue';
import { supportedFormats } from '../config';

interface AdaptiveMode {
	media: string;
	modifier: string;
}

interface Props {
	src: string;
	alt: string;
	classlist?: string;
	formats?: string | string[];
	draggable?: boolean;
	lazy?: boolean;
	sizes?: number | number[];
	adaptiveModes?: AdaptiveMode[];
}
const { src, alt, classlist, lazy, sizes, formats, draggable, adaptiveModes } = defineProps<Props>();

const requestedFormats = formats ? (typeof formats === 'string') ? formats.replace('\s','').split(',') : formats : [];
const imageAltFormats = supportedFormats.filter(format => requestedFormats.some(item => item.toLowerCase() === format));

const sources = imageAltFormats.map(format => ({
	source: `${src.replace(/\.[\w\d]+/, '')}.${format}`,
	type: `image/${format}`,
	media: null
}));

const adaptiveSources = adaptiveModes?.map(sourceMedia => sources.map(sourceFormats => {
	const { source } = sourceFormats;
	sourceFormats.media = sourceMedia.media;
	sourceFormats.source = source.replace(/\..*$/, '') + sourceMedia.modifier + source.match(/\..*$/)?.[0];
	return sourceFormats;
})).flat(2);

const useSources = adaptiveSources?.length ? adaptiveSources : sources;

</script>

<template>

	<picture :class="classlist" data-maddsua-component="vue:ssgassets:picture">
		<source v-for="item of useSources" :srcset="item.source" :type="item.type" :media="`(${item.media})`" />
		<Img :src="src" :alt="alt" :draggable="draggable" :lazy="lazy" :sizes="sizes" />
	</picture>

</template>

// src/components/Picture.tsx
import Img from "./Img.jsx";

interface Props {
	src: string;
	alt: string;
	classlist?: string;
	formats?: string | string[];
	draggable?: boolean;
	lazy?: boolean;
	sizes?: number | number[];
}

export default ({src, alt, classlist, lazy, sizes, formats, draggable}: Props) => {

	return (
		<picture className={classlist}>
			{ ((typeof formats === 'string') ? formats.replace('\s','').split(',') : formats)?.map((format, index) => (
				<source key={`src_${index}`} srcSet={ (src.replace(/\.[\w\d]+/, '.') + format) } type={ `image/${format}` } />
			)) }
			<Img src={src} alt={alt} draggable={draggable} lazy={lazy} sizes={sizes} />
		</picture>
	);
}
